include:
  - project: 'devops-campus/ci-cd/ci-helpers'
    ref: main
    file: 
      - 'ci-helpers.yml'
  - project: 'devops-campus/ci-cd/cd-helpers'
    ref: main
    file: 
      - 'cd-helpers.yml'

stages:
  - restore
  - analyze
  - docker
  - approve
  - merge-request
  - dev
  - prod
  - wipe

Restore Database:
  extend: .db_restore
  stage: restore

Backend Test and Build:
  extend: .anal_backend
  stage: analyze

Frontend Test and Build:
  extend: .anal_frontend
  stage: analyze

Docker Build Ikea:
  extends: .docker_ikea
  stage: docker

Docker Build Verila:
  extends: .docker_verila
  stage: docker

Deploy Test Ikea:
  extends: .deploy_test_ikea
  stage: approve
  needs:
   - job: Docker Build Ikea

Deploy Test Verila:
  extends: .deploy_test_verila
  stage: approve
  needs:
   - job: Docker Build Verila

# Develop:
#   extends: .devmr
#   stage: merge-request
#   when:
#     - manual

# Deploy Stage:
#   extends: .deploy_dev
#   stage: dev
#   if:
#     - '$CI_MERGE_REQUEST_APPROVED == true && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == develop'

# Deploy Master:
#   extends: .master
#   stage: prod
#   if:
#     - '$GITLAB_USER_LOGIN == $AUTHORIZED_USERS'
#     - '$CI_MERGE_REQUEST_APPROVED == true && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == master'

Clear Environment Ikea:
  extends: .clear-env-ikea
  stage: wipe
  needs:
   - job: Deploy Test Ikea

Clear Environment Verila:
  extends: .clear-env-verila
  stage: wipe
  needs:
   - job: Deploy Test Verila