include:
  - project: 'devops-campus/ci-cd/ci-helpers'
    ref: main
    file: 
      - 'ci-helpers.v2.yml'
  - project: 'devops-campus/ci-cd/cd-helpers'
    ref: main
    file: 
      - 'cd-helpers.v2.yml'
  - project: 'optimal-projects/optimal/ci-automation'
    ref: main
    file:
      - 'automation-helpers.yml'

stages:
  - backup
  - restore
  - analyze
  - tag
  - build
  - select-test-machine
  - deploy
  - clear
  - rollback

Daily Backups:
  extends: .ikea-daily-backups
  stage: backup

Restore Database:
  extends: .clear-test-and-db-restore
  stage: restore

Backend Analyze:
 extends: .analyze-backend
 stage: analyze

Frontend Analyze:
 extends: .analyze-frontend
 stage: analyze

Create Tag and Select environment:
  extends: .create-tag-and-select-environment
  stage: tag

HotFix Build Tag:
  extends: .hotfix-build-tag
  stage: tag

Build Ikea:
  extends: .build-step
  stage: build
  variables:
    PROJECT: "ikea"
    environment: "test"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $HOTFIX_DEPLOYMENT == "true" && $PROJECT == "ikea"'
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_IKEA == "true"'
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_IKEA == "true" && ($CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH =~ ".+\/hotfix\/.+")'
      variables:
        environment: "production"
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_IKEA == "true" && ($CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH =~ ".+\/release\/.+")'
      variables:
        environment: "stage"

Build Verila:
  extends: .build-step
  stage: build
  variables:
    PROJECT: "verila"
    environment: "test"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $HOTFIX_DEPLOYMENT == "true" && $PROJECT == "verila"'
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_VERILA == "true"'
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_VERILA == "true" && ($CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH =~ ".+\/hotfix\/.+")'
      variables:
        environment: "production"
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_VERILA == "true" && ($CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH =~ ".+\/release\/.+")'
      variables:
        environment: "stage"

Build KTI:
  extends: .build-step
  stage: build
  variables:
    PROJECT: "kti"
    environment: "test"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $HOTFIX_DEPLOYMENT == "true" && $PROJECT == "kti"'
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_KTI == "true"'
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_KTI == "true" && ($CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH =~ ".+\/hotfix\/.+")'
      variables:
        environment: "production"
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_KTI == "true" && ($CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH =~ ".+\/release\/.+")'
      variables:
        environment: "stage"

Select Test Machine:
  extends: .select-test-machine
  stage: select-test-machine
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && ($DEPLOY_IKEA == "true" || $DEPLOY_VERILA == "true") && ($CI_COMMIT_BRANCH != "master" || $CI_COMMIT_BRANCH !~ ".+\/hotfix\/.+" || $CI_COMMIT_BRANCH != "develop" || $CI_COMMIT_BRANCH !~ ".+\/release\/.+")'
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $environment == "test" && ($HOTFIX_DEPLOYMENT == "true" && $PROJECT == "ikea" || $HOTFIX_DEPLOYMENT == "true" && $PROJECT == "verila")'

Deploy Ikea:
  extends: .deploy-step
  stage: deploy
  needs:
    - job: Select Test Machine
      optional: true
    - Build Ikea
  variables:
    PROJECT: "ikea"
    environment: "test"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $HOTFIX_DEPLOYMENT == "true" && $PROJECT == "ikea"'
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_IKEA == "true"'
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_IKEA == "true" && ($CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH =~ ".+\/hotfix\/.+")'
      variables:
        environment: "production"
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_IKEA == "true" && ($CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH =~ ".+\/release\/.+")'
      variables:
        environment: "stage"

Deploy Verila:
  extends: .deploy-step
  stage: deploy
  needs:
    - job: Select Test Machine
      optional: true
    - Build Verila
  variables:
    PROJECT: "verila"
    environment: "test"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_VERILA == "true" && ($CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH =~ ".+\/hotfix\/.+")'
      variables:
        environment: "production"
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_VERILA == "true" && ($CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH =~ ".+\/release\/.+")'
      variables:
        environment: "stage"
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $HOTFIX_DEPLOYMENT == "true" && $PROJECT == "verila"'
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_VERILA == "true"'

Deploy KTI:
  extends: .deploy-step
  stage: deploy
  needs:
    - Build KTI
  variables:
    PROJECT: "kti"
    environment: "test"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $HOTFIX_DEPLOYMENT == "true" && $PROJECT == "kti"'
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_KTI == "true"'
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_KTI == "true" && ($CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH =~ ".+\/hotfix\/.+")'
      variables:
        environment: "production"
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_KTI == "true" && ($CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH =~ ".+\/release\/.+")'
      variables:
        environment: "stage"

Clear Test environment:
  extends: .clear-test-environments
  stage: clear
  needs:
   - Select Test Machine
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && ($DEPLOY_IKEA == "true" || $DEPLOY_VERILA == "true") && ($CI_COMMIT_BRANCH != "master" || $CI_COMMIT_BRANCH !~ ".+\/hotfix\/.+" || $CI_COMMIT_BRANCH != "develop" || $CI_COMMIT_BRANCH !~ ".+\/release\/.+")'
      when: manual
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $environment == "test" && ($HOTFIX_DEPLOYMENT == "true" && $PROJECT == "ikea" || $HOTFIX_DEPLOYMENT == "true" && $PROJECT == "verila")'
      when: manual

# Rollback Stage:
#   extends: .rollback-stage
#   stage: rollback

# Rollback Prod:
#   extends: .rollback-prod
#   stage: rollback