include:
  - project: 'devops-campus/ci-cd/ci-helpers'
    ref: refactor-ci
    file: 
      - 'ci-helpers.yml'
  - project: 'devops-campus/ci-cd/cd-helpers'
    ref: refactor-cd
    file: 
      - 'cd-helpers.yml'
  - project: 'optimal-projects/optimal/ci-automation'
    ref: main
    file:
      - 'automation-helpers.yml'

stages:
  - backup
  - restore
  - analyze
  - tag
  - build
  - select-test-machine
  - deploy
  - clear
  - rollback

Daily Backups:
  extends: .ikea-daily-backups
  stage: backup

Restore Database:
  extends: .clear-test-and-db-restore
  stage: restore

Backend Analyze:
 extends: .analyze-backend
 stage: analyze

Frontend Analyze:
 extends: .analyze-frontend
 stage: analyze

Create Tag and Select environment:
  extends: .create-tag-and-select-environment
  stage: tag

HotFix Build Tag:
  extends: .hotfix-build-tag
  stage: tag

Build Ikea:
  extends: .build-step
  stage: build
  variables:
    PROJECT: "ikea"

Build Verila:
  extends: .build-step
  stage: build
  variables:
    PROJECT: "verila"

Build KTI:
  extends: .build-step
  stage: build
  variables:
    PROJECT: "kti"

Select Test Machine:
  extends: .select-test-machine
  stage: select-test-machine

Deploy Ikea:
  extends: .deploy-step
  stage: deploy
  needs:
   - Build Ikea
  variables:
    PROJECT: "ikea"

Deploy Verila:
  extends: .deploy-step
  stage: deploy
  needs:
   - Build Verila
  variables:
    PROJECT: "verila"

Deploy KTI:
  extends: .deploy-step
  stage: deploy
  needs:
    - Build KTI
  variables:
    PROJECT: "kti"

Clear Test environment:
  extends: .clear-test-environments
  stage: clear
  needs:
   - Select Test Machine

# Rollback Stage:
#   extends: .rollback-stage
#   stage: rollback

# Rollback Prod:
#   extends: .rollback-prod
#   stage: rollback